ALTER TABLE base_price_change_request
    ADD COLUMN IF NOT EXISTS version BIGINT,

    ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL,

    ADD COLUMN IF NOT EXISTS created_by VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255) NOT NULL,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    ADD COLUMN IF NOT EXISTS tenant_id BIGINT NOT NULL,
    ADD COLUMN IF NOT EXISTS store_id BIGINT NOT NULL,
    ADD COLUMN IF NOT EXISTS sku_id BIGINT NOT NULL,
    ADD COLUMN IF NOT EXISTS user_seg_id BIGINT NOT NULL,

    ADD COLUMN IF NOT EXISTS channel_id BIGINT,

    ADD COLUMN IF NOT EXISTS start_at_utc TIMESTAMP WITH TIME ZONE NOT NULL,

    ADD COLUMN IF NOT EXISTS base_price NUMERIC(19, 4) NOT NULL,

    ADD COLUMN IF NOT EXISTS reason TEXT,
    ADD COLUMN IF NOT EXISTS reject_reason TEXT;
