spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodapp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Admin123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: update   # 开发环境用 update，自动建表；上线建议改成 validate
    show-sql: true       # 控制台打印 SQL
    properties:
      hibernate:
        format_sql: true

server:
  port: 8900

grpc:
  server:
    port: 9090

debug: true

management:
  endpoint:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /actuator
  endpoints:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
  prometheus:
    metrics:
      export:
        enabled: true

