spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: Admin123!
      database: priceSnapshot
      authentication-database: admin

server:
  port: 8900  # RESTful HTTP port (Tomcat)

grpc:
  server:
    port: 9090  # gRPC server port

debug: true

management:
  endpoint:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /actuator
  endpoints:
    health:
      show-details: always
      probes:
          enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
  prometheus:
    metrics:
      export:
        enabled: true
